"""first try...

Revision ID: 01403f2687a7
Revises: beed67b87b6b
Create Date: 2023-03-28 01:15:07.078786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01403f2687a7'
down_revision = 'beed67b87b6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
