"""try to add tables and first entries

Revision ID: deb0a47d1631
Revises: 01403f2687a7
Create Date: 2023-03-28 01:17:00.759752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb0a47d1631'
down_revision = '01403f2687a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
